Refactor/new sseussak
sungbinland/sseukssak pull request #13
Opened 2022-09-02 11:33 UTC by ChangXXX

## 변경 사항

> 1. navigation 추가했습니다. (sseukssak list to create sseukssak)
2. LoginRepository에 getUserId 추가했습니다.
3. Sseukssak model id 생성, 작성자 id 변수 추가
4. NewSseukssakRepository 삭제하고 기존 SseukssakListRepository에 합쳤습니다.
5. 이름변경 SseukssakListRepository -> SseukssakRepository

## 결과 사진

> Ui 변경 없습니다.

2022-09-02 19:48 UTC, jisungbin requested changes
수고하셨어요! userId 실패 부분은 처리하는게 좋아 보여요

2022-09-02 19:48 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/login/LoginRepositoryImpl.kt
>      private val preference: SharedPreferences
SharedPreferences 보다는 DataStore 쓰시면 좀 더 모던하게 안드로이드 개발 하실 수 있어요!
알고 계세용

2022-09-02 19:48 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/sseukssak/model/Sseukssak.kt
> +    val date: String = "".getCurrTime(),
date 는 `Date().time` 해서 Long 으로 받는게 어떨까요?

2022-09-02 19:48 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/sseukssak/repository/SseukssakRepository.kt
> +     * @return 쓱싹 생성하기가 성공되면 성공 메세지가 반환되고, 실패하면 Exception이  반환된다.
KDoc 잘 달아주셨네요!
근데 `성공 메세지가 반환` 에서 왜 성공시 메시지를 넘겨주게 하셨나요?
꼭 성공 여부를 알려줘야 한다면 그냥 Unit 이나 true 도 괜찮을거 같아요.

2022-09-02 19:48 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/sseukssak/repository/SseukssakRepositoryImpl.kt
> +    @OptIn(ExperimentalCoroutinesApi::class)
@OptIn(ExperimentalCoroutinesApi::class)

필요 없습니당

2022-09-02 19:48 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/create/CreateSseukssakViewModel.kt
> +                wroteUserId = userId!!
`userId!!` 말고, `userId ?: throw IllegalStateException("userId 가 잘못됐습니다.")` 같이 직접 에러를 알리는게 어떨까요?
아니면 UiState 로 실패 state 를 넘겨서 UI 단에서 처리해야 좋을거 같아요. <-- 이게 정답 같네요

2022-09-02 19:48 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/util/extensions/string.kt
> +fun String.generateId(): String {
String 을 receiver 로 받으신 이유가 있나요? receiver 가 안쓰이는거 같아서요!

2022-09-02 19:48 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/util/extensions/string.kt
> +    return (1..10).map { charSet.random() }.joinToString("")
`(1..10).map { charSet.random() }.joinToString("")` 에서 `(1..0)` 으로 사용하지 않는 Array 를 만들기 보다는
`Array(10) { charSet.random() }.joinToString("")` 으로 Array 생성을 `charSet.random()` 으로 하는게 더 좋아 보여요

2022-09-02 19:48 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/util/extensions/string.kt
> +fun String.getCurrTime(): String {
위 `generateId()` 와 같이 String 이 안쓰인거 같아여
String 에 확장 함수로 만들고 싶으시다면 `String.Companion.getCurrentDate()` 같이 가능합니다.

2022-09-02 19:48 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/util/extensions/string.kt
> +fun String.getCurrTime(): String {
<img width="1618" alt="image" src="https://user-images.githubusercontent.com/40740128/188226214-3ba40733-8347-4f02-aa7b-6a66ab79aca6.png">

2022-09-02 19:53 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/util/extensions/string.kt
> +fun String.generateId(): String {
참고로 랜덤 키 생성하는거 `UUID` 객체로도 하실 수 있어요!

```kotlin
fun main() {
    println(UUID.randomUUID().toString())
    // 4b4ac8fe-9c2b-4675-bef1-3143d3b3f3d5
}
```

2022-09-04 14:26 UTC, ChangXXX commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/sseukssak/model/Sseukssak.kt
> +    val date: String = "".getCurrTime(),
Firestore에 Timestamp 가 있어 Timestamp 로 변경하겠습니당

2022-09-04 23:43 UTC, jisungbin approved these changes
수고하셨어요! 지금은 쓱싹 추가하는 부분만 구현하신거죠? 이번에도 창민님이 봐보시구 머지 해주시면 댐니당

2022-09-05 05:47 UTC, merged