Feature/splash kakao login
sungbinland/sseukssak pull request #2
Opened 2022-06-01 19:57 UTC by mangbaam

## 변경 사항

- Splash 화면 추가
- Kakao 로그인 추가

## 결과 사진

> <img src="https://user-images.githubusercontent.com/44221447/171490148-91ca7d38-0301-4022-9f95-44a20f5c11d6.gif" width="33%" />

2022-06-09 12:00 UTC, jisungbin commented
수고하셨어요! 감사합니다 🙇‍♂️

2022-06-10 13:51 UTC, jisungbin requested changes

2022-06-10 13:51 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/SseukSsak.kt
> +        KakaoSdk.init(this, KAKAO_API_KEY)
BuildConfig.KAKAO_API_KEY

2022-06-10 13:51 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/activity/LoginActivity.kt
> +            UserApiClient.instance.accessTokenInfo { tokenInfo, error ->
suspendCancallableCoroutine

2022-06-10 13:51 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/activity/LoginViewModel.kt
> +        data class KakaoLogin(val p: Unit) : Event()
p 인자?

2022-06-10 13:51 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/activity/LoginViewModel.kt
> +        data class SkipLogin(val p: Unit) : Event()
object 로 변경 해주세요

2022-06-10 13:51 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/activity/LoginViewModel.kt
> +        data class SkipLogin(val p: Unit) : Event()
Event 클래스 분리

2022-06-10 13:51 UTC, jisungbin commented on presentation/src/main/res/layout/activity_login.xml
> +            android:textColor="#CC343434"
color 리소스 분리

2022-06-10 13:51 UTC, jisungbin commented on presentation/src/main/res/layout/activity_login.xml
> +                android:contentDescription="@string/activity_login_description_kakao_symbol" />
@null

2022-06-10 14:46 UTC, jisungbin requested changes
수정 필요

2022-06-23 06:38 UTC, mangbaam commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/util/extensions/Lifecycle.kt
> +    lifecycleScope.launch {
launch로 유지

2022-06-24 13:14 UTC, mangbaam commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/activity/LoginActivity.kt
> +            UserApiClient.instance.accessTokenInfo { tokenInfo, error ->
이 부분은 어떻게 적용해야 할 지 모르겠어서 변경하지 못했습니다

2022-06-24 14:30 UTC, jisungbin approved these changes
수고하셨습니당

2022-06-24 14:30 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/activity/login/LoginActivity.kt
> + * SseukSsak license is under the MIT.
copyright 2개!

2022-06-24 14:30 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/activity/login/LoginActivity.kt
> +                LoginState.LOG_OUT -> {}
네이밍 규칙 하나로 통일하고자 파스칼로도 나쁘지 않음

2022-06-24 14:30 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/activity/login/LoginActivity.kt
> +        Log.d("LoginActivity", "로그인 건너 뛰기")
로깅 라이브러리 logeukes 있습니당,,

2022-06-24 14:30 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/activity/login/LoginViewModel.kt
> + * Please see: https://github.com/sungbinland/sseukssak/blob/main/LICENSE.
카피라이트 2개

2022-06-24 14:30 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/activity/login/LoginActivity.kt
> +        UserApiClient.instance.loginWithKakaoTalk(this) { token, error ->
여기서 로그인 성공하면 me 에서 내 계정 아이디 가져와서 내부 SharedPreference or DataStore(코루틴 사용) 에 저장

2022-06-24 14:30 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/activity/login/LoginViewModel.kt
> +    fun checkLoginState(state: (LoginState) -> Unit) {
없애기 XXX

SharedPreference 에 저장된 유저 아이디로 자동 로그인 체크

2022-06-24 14:30 UTC, jisungbin commented on presentation/src/main/res/drawable/bg_kakao_login_button.xml
> +<shape xmlns:android="http://schemas.android.com/apk/res/android" android:shape="rectangle">
코드 정렬? 안된걸로 보여용

2022-06-24 14:30 UTC, jisungbin commented on presentation/src/main/res/layout/activity_login.xml
> +        <androidx.appcompat.widget.LinearLayoutCompat
Compat XXX

2022-06-24 14:30 UTC, jisungbin commented on presentation/src/main/res/layout/activity_login.xml
> +                android:layout_width="17dp"
16 x 16 정사각형

2022-06-24 14:30 UTC, jisungbin commented on presentation/src/main/res/layout/activity_login.xml
> +                app:layout_constraintTop_toTopOf="parent" />
\n

2022-06-24 14:32 UTC, merged