Feature/search
sungbinland/sseukssak pull request #4
Opened 2022-06-10 01:29 UTC by ckrudals

## 변경 사항

> UiState 추가
> Room search 저장 및 삭제
> data package 추가
> Search layout, item, adapter 추가
> Room, repository module 추가

## 결과 사진

 
 <img src="https://user-images.githubusercontent.com/68880067/172971945-62a016d0-da75-4237-858c-fadae549653c.gif" width="33%" />

2022-06-10 01:30 UTC, jisungbin commented
수고하셨어요! 감사합니다 🙇‍♂️

2022-06-10 14:47 UTC, jisungbin requested changes
코드 리뷰

2022-06-10 14:47 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/SearchRepository.kt
> +/*
XXXX

2022-06-10 14:47 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/SearchRepository.kt
> +
KDoc 문서화

2022-06-10 14:47 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/db/SearchEntity.kt
> +    var id: Int = 0
SearchEntity 인자로 합치기

2022-06-10 14:47 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/di/DatabaseModule.kt
> +    ): SearchDataBase =
synchronized 처리

2022-06-10 14:47 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/db/SearchEntity.kt
> +    var id: Int = 0
val

2022-06-10 14:47 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchFragment.kt
> +            layoutManager = LinearLayoutManager(requireContext())
app:layoutManager = LinearLayoutManager
android:orientation = vertical

2022-06-10 14:47 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchViewModel.kt
> +    fun insertSearch(entity: SearchEntity) = viewModelScope.launch {
```kt
fun insertSearch() {
  viewModelScope.launch {
~~
}
}
```

2022-06-10 14:47 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchViewModel.kt
> +        repository.getSearchAll()
Flow.catch

2022-06-10 14:47 UTC, jisungbin commented on presentation/src/main/res/layout/fragment_search.xml
> +        android:layout_marginStart="22dp"
22dp

2022-06-12 10:32 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/SearchRepository.kt
> +/*
완료

2022-06-12 10:32 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/db/SearchEntity.kt
> +    var id: Int = 0
완료

2022-06-12 10:33 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/di/RepositoryModule.kt
> +    fun provideSearchRepository(dao: SearchDao): SearchRepository {
완료

2022-06-12 10:34 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/di/RepositoryModule.kt
> +@InstallIn(SingletonComponent::class)
완료

2022-06-12 10:34 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchAdapter.kt
> +    diffUtil
완료

2022-06-12 10:35 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchFragment.kt
> +                    searchViewModel.insertSearch(SearchEntity(searchText = query ?: ""))
완료

2022-06-12 10:35 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchFragment.kt
> +            layoutManager = LinearLayoutManager(requireContext())
완료

2022-06-12 10:35 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/util/UiState.kt
> +    data class Error(val error: Throwable?):UiState<Nothing>()
완료

2022-06-12 10:35 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchViewModel.kt
> +    fun insertSearch(entity: SearchEntity) = viewModelScope.launch {
완료

2022-06-12 10:35 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchViewModel.kt
> +
완료

2022-06-12 10:53 UTC, ckrudals commented on presentation/src/main/res/layout/fragment_search.xml
> +        android:layout_marginStart="22dp"
완료

2022-06-16 03:10 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchAdapter.kt
> +    companion object {
완료

2022-06-16 03:10 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchFragment.kt
> +                lifecycleScope.launch {
완료

2022-06-16 03:11 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchFragment.kt
> +        lifecycleScope.launch {
완료

2022-06-16 03:11 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchFragment.kt
> +            searchViewModel.getAllSearch().collect {
완료

2022-06-16 03:22 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchFragment.kt
> +                        Log.d("TAG", "getAllSearch: 성공 : ${it.data}")
완료

2022-06-16 03:23 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchViewModel.kt
> +        repository.getSearchAll()
현재 repository 단에서 catch로 예외처리를 하고 있는데
viewModel 단으로 옮겨야 할까요?
- SearchRepositoryImpl
```kotlin
 override fun getSearchAll() = flow {
        emit(UiState.Loading)
        dao.getSearchAll().collect {
            emit(UiState.Success(it))
        }
    }.catch { e ->
        emit(UiState.Error(e))

    }
```

2022-06-17 04:23 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/di/DatabaseModule.kt
> +    ): SearchDataBase =
완료

2022-06-24 15:41 UTC, jisungbin requested changes
코드 리뷰

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/SearchRepository.kt
> +    suspend fun insertSearch(entity: SearchEntity)
**Search**Repository 인데 굳이 또 Search 를 명시 해줘야 하나 싶음

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/SearchRepository.kt
> +    suspend fun deleteSearch(idx: Int)
index 풀네임 지향

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/db/SearchDao.kt
> +/*
2번

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/db/SearchDao.kt
> +    suspend fun insertSearch(entity: SearchEntity)
Search 명명 생략

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/db/SearchDataBase.kt
> +/*
2번

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/db/SearchDao.kt
> +    suspend fun insertSearch(entity: SearchEntity)
쿼리문 설명만 KDoc 추가

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/db/SearchDataBase.kt
> +    companion object{
object {

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/db/SearchEntity.kt
> +/*
2222

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/db/SearchEntity.kt
> +    companion object {
테이블 이름 정의가 필요한지?

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/db/SearchEntity.kt
> +    val id: Int
id 는 기본값 0 같은걸로 넣어줘야 autoGenerate 효과를 얻어서 매번 인스턴스 만들 때 마다 인자를 안 넣어줘도 됨

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/di/RepositoryModule.kt
> +    fun provideSearchRepository(dao: SearchDao) = SearchRepositoryImpl(dao)
fun provideSearchRepository(dao: SearchDao): SearchRepository = SearchRepositoryImpl(dao)

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchAdapter.kt
> +        holder.binding.deleteSearchImg.setOnClickListener { deleteItem.onclick(getItem) }
람다식 시작과 끝 \n

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchFragment.kt
> +            android.widget.SearchView.OnQueryTextListener {
똑같은거 2개

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchFragment.kt
> +            override fun onQueryTextChange(newText: String?): Boolean {
= true

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchFragment.kt
> +            searchViewModel.getAllSearch().flowWithLifecycle(lifecycle, Lifecycle.State.STARTED)
lifecycle -> viewLifecycleOwner.lifeCycle

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchViewModel.kt
> +    init {
무슨 의도로 하신건지 파악 불가능

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/data/search/db/SearchDao.kt
> +    fun getSearchAll(): Flow<List<SearchEntity>>
suspend

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchViewModel.kt
> +        repository.getSearchAll()
네

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchViewModel.kt
> +                initialValue = UiState.Uninitialized
하실거면 sharedIn 이 맞았고, UiState.Uninitialized 는 필요 없음

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchViewModel.kt
> +            .stateIn(
XXX

2022-06-24 15:41 UTC, jisungbin commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/util/UiState.kt
> +    object Uninitialized : UiState<Nothing>()
: 스타일 이렇게 통일

2022-06-24 16:42 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchFragment.kt
> +            android.widget.SearchView.OnQueryTextListener {
완료

2022-06-24 16:43 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchFragment.kt
> +                    searchViewModel.insertSearch(SearchEntity(searchText = query.orEmpty(), 0))
완료

2022-06-24 16:43 UTC, ckrudals commented on presentation/src/main/kotlin/team/sungbinland/sseukssak/fragment/search/SearchFragment.kt
> +            override fun onQueryTextChange(newText: String?): Boolean {
완료

2022-07-01 12:46 UTC, merged